import esbuild from "esbuild";
import { readFileSync } from "fs";
import process from "process";
import { builtinModules as builtins } from "node:module";

const manifest = JSON.parse(
  readFileSync(new URL('./manifest.json', import.meta.url), 'utf-8')
);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/*",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
})
  .then(() => {
    if (prod) {
      console.log(`✅ Built ${manifest.name} v${manifest.version} (production)`);
    } else {
      console.log(`✅ Built ${manifest.name} (development)`);
    }
  })
  .catch(() => process.exit(1));