import ResuperchargedLinks from "../main";
import { sanitizeRule } from "./rule-sanitizer";
import { CSSLink, matchSign, MatchTypes } from "../types/css-link"
import { escCssString, processKey } from "../utils/string-utils";


/**
 * Compiles a user-defined rule template into a concrete CSS attribute selector fragment.
 *
 * @example
 * - [data-link-tags*="foo" i]
 * - [data-link-path="Note.md"]
 * - [data-link-project-name^="abc" i]
 */
function compileCssSelector(selector: CSSLink): string {
  const isSensitive = selector.matchCaseSensitive ? "" : " i";
  const op = matchSign[selector.match] || "*=";

  if (selector.type === "attribute") {
    // 2. DEDUPLICATED: Replaced local workspace implementation with centralized processKey utility
    const normalizedName = processKey(selector.name || "");
    if (!normalizedName) return `[data-link-path*="__never__"]`;
    const value = escCssString((selector.value || "").trim());
    return `[data-link-${normalizedName}${op}"${value}"${isSensitive}]`;
  }

  if (selector.type === "tag") {
    const value = escCssString((selector.value || "").trim());
    return `[data-link-tags*="${value}" i]`;
  }

  // Note Path Fallback: Always default to an internal substring lookup matcher
  const raw = (selector.value || "").trim();
  if (!raw) return `[data-link-path*="__never__"]`;

  return `[data-link-path*="${escCssString(raw)}"${isSensitive}]`;
}

/**
 * Builds the visual property blocks (colors, font styles) for a specific target rule.
 */
function buildStyleBlock(selector: CSSLink, cssSelector: string, outputLines: string[]): void {
  const lightColor = (selector.lightColor || "").trim();
  const darkColor = (selector.darkColor || "").trim();
  const hasAnyColor = !!lightColor || !!darkColor;

  const lightBg = (selector.lightBgColor || "").trim().toLowerCase();
  const darkBg  = (selector.darkBgColor || "").trim().toLowerCase();
  const hasAnyBg = (lightBg !== "" && lightBg !== "transparent") || (darkBg !== "" && darkBg !== "transparent");

  const hasWeight = selector.fontWeight && selector.fontWeight !== "normal";
  const hasStyle = selector.fontStyle && selector.fontStyle !== "normal";

  // Performance Optimization: Short-circuit entire text generation block if the rule is empty
  if (!hasAnyColor && !hasAnyBg && !hasWeight && !hasStyle) return;

  // Append comma-separated text targets directly to minimize array joining over loops
  outputLines.push(`.data-link-text${cssSelector},\n.data-link-text${cssSelector} .cm-underline {`);

  if (hasAnyColor) outputLines.push(`    color: var(--scl-color-${selector.uid}) !important;`);
  if (hasAnyBg) outputLines.push(`    background-color: var(--scl-bg-${selector.uid}) !important;`);
  if (hasWeight) outputLines.push(`    font-weight: ${selector.fontWeight} !important;`);
  
  if (selector.fontStyle === "italic") {
    outputLines.push(`    font-style: italic !important;`);
  } else if (selector.fontStyle === "underline") {
    outputLines.push(`    text-decoration: underline !important;`);
  } else if (selector.fontStyle === "line-through") {
    outputLines.push(`    text-decoration: line-through !important;`);
  }

  outputLines.push(`}`);
}

/**
 * Compiles prepend and append icon pseudo-elements for active links.
 */
function buildIconBlocks(selector: CSSLink, cssSelector: string, outputLines: string[]): void {
  const before = escCssString(selector.iconBefore || "");
  const after = escCssString(selector.iconAfter || "");

  if (before) outputLines.push(`.data-link-text${cssSelector}::before { content: "${before}"; }`);
  if (after) outputLines.push(`.data-link-text${cssSelector}::after { content: "${after}"; }`);
}

/**
 * Main CSS orchestration engine.
 * Generates runtime CSS properties and saves them directly to Obsidian's snippet directory.
 */
export async function buildCSS(selectors: CSSLink[], plugin: ResuperchargedLinks): Promise<void> {
  const instructions: string[] = [
    "/* WARNING: Dynamically generated by re-supercharged-links. Do not edit directly. */",
    ""
  ];

  const lightVars: string[] = [".theme-light {"];
  const darkVars: string[] = [".theme-dark {"];
  const rules: string[] = [""];

  // 3. PERFORMANCE OPTIMIZATION: Mutate a shared array buffer reference instead of generating thousands of mini-arrays
  for (const rawSelector of selectors) {
    if (!rawSelector) continue;
    const selector = sanitizeRule(rawSelector);
    const cssSelector = compileCssSelector(selector);

    lightVars.push(
      `    --scl-color-${selector.uid}: ${selector.lightColor || "var(--text-normal)"};`,
      `    --scl-bg-${selector.uid}: ${selector.lightBgColor || "transparent"};`
    );

    darkVars.push(
      `    --scl-color-${selector.uid}: ${selector.darkColor || "var(--text-normal)"};`,
      `    --scl-bg-${selector.uid}: ${selector.darkBgColor || "transparent"};`
    );

    buildStyleBlock(selector, cssSelector, rules);
    buildIconBlocks(selector, cssSelector, rules);
  }

  // Global Guards: Suppress pseudo-icons automatically when runtime applies hide overrides
  rules.push(
    "",
    ".data-link-text.scl-hide-before::before { content: \"\" !important; }",
    ".data-link-text.scl-hide-after::after { content: \"\" !important; }"
  );

  lightVars.push("}");
  darkVars.push("}");

  const finalCSS = [...instructions, ...lightVars, "", ...darkVars, ...rules].join("\n");

  const vault = plugin.app.vault;
  const configDir = vault.configDir;
  const snippetsDir = `${configDir}/snippets`;
  const snippetPath = `${snippetsDir}/re-supercharged-links-gen.css`;

  // Safely provision filesystem adapters to handle directories and write file buffers atomic
  await vault.adapter.mkdir(snippetsDir);
  await vault.adapter.write(snippetPath, finalCSS);

  if (plugin.settings.activateSnippet) {
    // @ts-ignore
    const customCss = plugin.app.customCss;
    if (customCss) {
      customCss.enabledSnippets.add("re-supercharged-links-gen");
      customCss.requestLoadSnippets();
    }
  }
}
