import { CSSLink } from "../types/css-link";
import ResuperchargedLinks from "../main";
import { sanitizeRule } from "./rule-sanitizer";
import { processKey, escCssString } from "../utils/string-utils";

function compileCssSelector(selector: CSSLink): string {
  const isSensitive = selector.matchCaseSensitive ? "" : " i";
  const op = selector.match === "exact" ? "=" : selector.match === "contains" ? "*=" : selector.match === "startswith" ? "^=" : selector.match === "endswith" ? "$=" : "~=";

  if (selector.type === "attribute") {
    const normalizedName = processKey(selector.name || "");
    if (!normalizedName) return `[data-link-path*="__never__"]`;
    return `[data-link-${normalizedName}${op}"${escCssString((selector.value || "").trim())}"${isSensitive}]`;
  }

  if (selector.type === "tag") {
    return `[data-link-tags*="${escCssString((selector.value || "").trim())}" i]`;
  }

  const raw = (selector.value || "").trim();
  if (!raw) return `[data-link-path*="__never__"]`;
  return `[data-link-path*="${escCssString(raw)}"${isSensitive}]`;
}

function buildStyleBlock(selector: CSSLink, cssSelector: string, outputLines: string[]): void {
  const lightColor = (selector.lightColor || "").trim();
  const darkColor = (selector.darkColor || "").trim();
  const hasAnyColor = !!lightColor || !!darkColor;

  const lightBg = (selector.lightBgColor || "").trim().toLowerCase();
  const darkBg  = (selector.darkBgColor || "").trim().toLowerCase();
  const hasAnyBg = (lightBg !== "" && lightBg !== "transparent") || (darkBg !== "" && darkBg !== "transparent");

  const hasWeight = selector.fontWeight && selector.fontWeight !== "normal";
  const hasStyle = selector.fontStyle && selector.fontStyle !== "normal";

  if (!hasAnyColor && !hasAnyBg && !hasWeight && !hasStyle) return;

  outputLines.push(`.data-link-text${cssSelector},\n.data-link-text${cssSelector} .cm-underline {`);
  if (hasAnyColor) outputLines.push(`    color: var(--scl-color-${selector.uid}) !important;`);
  if (hasAnyBg) outputLines.push(`    background-color: var(--scl-bg-${selector.uid}) !important;`);
  if (hasWeight) outputLines.push(`    font-weight: ${selector.fontWeight} !important;`);
  
  if (selector.fontStyle === "italic") {
    outputLines.push(`    font-style: italic !important;`);
  } else if (selector.fontStyle === "underline") {
    outputLines.push(`    text-decoration: underline !important;`);
  } else if (selector.fontStyle === "line-through") {
    outputLines.push(`    text-decoration: line-through !important;`);
  }
  outputLines.push(`}`);
}

function buildIconBlocks(selector: CSSLink, cssSelector: string, outputLines: string[]): void {
  const before = escCssString(selector.iconBefore || "");
  const after = escCssString(selector.iconAfter || "");

  if (before) outputLines.push(`.data-link-text${cssSelector}::before { content: "${before}"; }`);
  if (after) outputLines.push(`.data-link-text${cssSelector}::after { content: "${after}"; }`);
}

export async function buildCSS(selectors: CSSLink[], plugin: ResuperchargedLinks): Promise<void> {
  const instructions: string[] = [
    "/* WARNING: Dynamically generated by re-supercharged-links. Do not edit directly. */",
    ""
  ];

  const lightVars: string[] = [".theme-light {"];
  const darkVars: string[] = [".theme-dark {"];
  const rules: string[] = [""];

  for (const rawSelector of selectors) {
    if (!rawSelector) continue;
    const selector = sanitizeRule(rawSelector);
    const cssSelector = compileCssSelector(selector);

    lightVars.push(
      `    --scl-color-${selector.uid}: ${selector.lightColor || "var(--text-normal)"};`,
      `    --scl-bg-${selector.uid}: ${selector.lightBgColor || "transparent"};`
    );

    darkVars.push(
      `    --scl-color-${selector.uid}: ${selector.darkColor || "var(--text-normal)"};`,
      `    --scl-bg-${selector.uid}: ${selector.darkBgColor || "transparent"};`
    );

    buildStyleBlock(selector, cssSelector, rules);
    buildIconBlocks(selector, cssSelector, rules);
  }

  // 🔑 SUPER-VEKT: Ved å koble klassen direkte på attributt-velgerne i CSS-en,
  // tvinger vi nettleseren til å fjerne doblingen momentant, helt uten !important på guarden!
  rules.push(
    "",
    "/* Global Multi-window Suppress Guards */",
    ".data-link-text.scl-hide-before::before, .data-link-text.scl-hide-before[data-link-tags]::before, .data-link-text.scl-hide-before[data-link-path]::before { content: \"\"; }",
    ".data-link-text.scl-hide-after::after, .data-link-text.scl-hide-after[data-link-tags]::after, .data-link-text.scl-hide-after[data-link-path]::after { content: \"\"; }"
  );

  lightVars.push("}");
  darkVars.push("}");

  const finalCSS = [...instructions, ...lightVars, "", ...darkVars, ...rules].join("\n");
  const vault = plugin.app.vault;
  const snippetsDir = `${vault.configDir}/snippets`;
  await vault.adapter.mkdir(snippetsDir);
  await vault.adapter.write(`${snippetsDir}/re-supercharged-links-gen.css`, finalCSS);

  if (plugin.settings.activateSnippet) {
    const customCss = (plugin.app as any).customCss;
    if (customCss) {
      customCss.enabledSnippets.add("re-supercharged-links-gen");
      customCss.requestLoadSnippets();
    }
  }
}
