import { CSSLink, matchSign } from "./cssLink";
import ResuperchargedLinks from "./main";

export async function buildCSS(selectors: CSSLink[], plugin: ResuperchargedLinks) {
    const instructions: string[] = [
        "/* WARNING: Dynamically generated by re-supercharged-links. Do not edit directly. */",
        ""
    ];

    let lightVars: string[] = [".theme-light {"];
    let darkVars: string[] = [".theme-dark {"];
    let rules: string[] = [""];

    selectors.forEach(selector => {
        // 1. Generer variablene for lys og mørk modus separat
        lightVars.push(`    --scl-color-${selector.uid}: ${selector.lightColor};`);
        darkVars.push(`    --scl-color-${selector.uid}: ${selector.darkColor};`);

        // 2. Bygg opp CSS-selektoren basert på type (tag, attributt eller filbane)
        let cssSelector: string;
        if (selector.type === 'attribute') {
            cssSelector = `[data-link-${selector.name}${matchSign[selector.match]}="${selector.value}" ${selector.matchCaseSensitive ? "" : " i"}]`;
        } else if (selector.type === 'tag') {
            cssSelector = `[data-link-tags*="${selector.value}" i]`;
        } else {
            cssSelector = `[data-link-path${matchSign[selector.match]}="${selector.value}" ${selector.matchCaseSensitive ? "" : "i"}]`;
        }
        // 3. Generer den modusuavhengige stylingen for tekstfarge, vekt og stil
        const textStyles: string[] = [
            `div[data-id="${selector.uid}"] div.setting-item-description,`,
            `${cssSelector} {`,
            `    color: var(--scl-color-${selector.uid}) !important;`
        ];

        // Sjekk og legg til tekstvekt hvis den ikke er normal (Tynn eller Kraftig)
        if (selector.fontWeight && selector.fontWeight !== "normal") {
            textStyles.push(`    font-weight: ${selector.fontWeight} !important;`);
        }

        // Sjekk og legg til tekststil (Kursiv, Understreket eller Overstrøket)
        if (selector.fontStyle === "italic") {
            textStyles.push(`    font-style: italic !important;`);
        } else if (selector.fontStyle === "underline") {
            textStyles.push(`    text-decoration: underline !important;`);
        } else if (selector.fontStyle === "line-through") {
            textStyles.push(`    text-decoration: line-through !important;`);
        }

        textStyles.push(`}`);
        rules.push(...textStyles);

        // 4. Generer logikk for ikon FØR lenken
        if (selector.iconBefore) {
            rules.push(...[
                `div[data-id="${selector.uid}"] div.setting-item-description::before,`,
                `.data-link-icon${cssSelector}::before {`,
                `    content: "${selector.iconBefore} " !important;`,
                `}`
            ]);
        }

        // 5. Generer logikk for ikon ETTER lenken
        if (selector.iconAfter) {
            rules.push(...[
                `div[data-id="${selector.uid}"] div.setting-item-description::after,`,
                `.data-link-icon-after${cssSelector}::after {`,
                `    content: " ${selector.iconAfter}" !important;`,
                `}`
            ]);
        }
    });
    lightVars.push("}");
    darkVars.push("}");

    // Kombiner absolutt alle genererte CSS-rader sammen
    const finalCSS = [...instructions, ...lightVars, "", ...darkVars, ...rules].join("\n");

    // Fysisk lagring til fil i hvelvets snippet-mappe
    const vault = plugin.app.vault;
    const configDir = vault.configDir ?? ".obsidian";
    const pathDir = configDir + "/snippets";
    await vault.adapter.mkdir(pathDir);
    const path = pathDir + "/supercharged-links-gen.css";
    
    if (await vault.adapter.exists(path)) {
        await vault.adapter.remove(path);
    }
    await vault.create(path, finalCSS);

    // Trigger den native oppdateringen i Obsidian i sanntid
    if (plugin.settings.activateSnippet) {
        // @ts-ignore
        const customCss = plugin.app.customCss;
        customCss.enabledSnippets.add('supercharged-links-gen');
        customCss.requestLoadSnippets();
    }
}
